#!/bin/sh

set -e

if [ -z "${DTC}" ]
then
	DTC=dtc
fi

dtc_me() {
	pushd "$1" >/dev/null
	TARGET_DIR="target/x86_64-unknown-none/release"
	mkdir -p "${TARGET_DIR}"
	FIXED_DTFS=fixed-dtfs.dtb
	"${DTC}" -W no-unit_address_vs_reg fixed-dtfs.dts -O dtb -o "${TARGET_DIR}/${FIXED_DTFS}"
	popd >/dev/null
}

dtc_me "${PWD}/src/mainboard/amd/romecrb"
dtc_me "${PWD}/src/mainboard/emulation/qemu-q35"
dtc_me "${PWD}/src/mainboard/asrock/a300m-stx"

if [ -z "${MAINBOARD}" ]
then
	MAINBOARD="src/mainboard/amd/romecrb"
fi

(cd "${MAINBOARD}" && as -c -o start.o start.S)
(cd "${MAINBOARD}" && objcopy -O binary start.o start.bin)

in-rust-nightly -w src/soc/amd/picasso cargo fmt --all
in-rust-nightly -w src/soc/amd/rome cargo fmt --all
in-rust-nightly -w src/soc/amd/common/df cargo fmt --all
in-rust-nightly -w src/soc/amd/common/pci cargo fmt --all
in-rust-nightly -w src/soc/amd/common/smn cargo fmt --all
#in-rust-nightly -w src/mainboard/amd/romecrb cargo fmt --all
#in-rust-nightly -w src/mainboard/asrock/a300m-stx cargo fmt --all
#in-rust-nightly clippy ...
../in-rust-nightly make OBJCOPY=objcopy -C "${MAINBOARD}" "$@"
#exec "`dirname $0`/pack"
#exec ../in-rust-nightly make OBJCOPY=objcopy -C src/mainboard/emulation/qemu-q35 "$@"
