#!/bin/sh

if [ -z "${DTC}" ]
then
	DTC=dtc
fi

dtc_me() {
	pushd "$1" >/dev/null
	TARGET_DIR="target/x86_64-unknown-none/release"
	mkdir -p "${TARGET_DIR}"
	FIXED_DTFS=fixed-dtfs.dtb
	"${DTC}" -W no-unit_address_vs_reg fixed-dtfs.dts -O dtb -o "${TARGET_DIR}/${FIXED_DTFS}"
	popd >/dev/null
}

dtc_me "${PWD}/src/mainboard/amd/romecrb"
dtc_me "${PWD}/src/mainboard/emulation/qemu-q35"

exec ../in-rust-nightly make OBJCOPY=objcopy -C src/mainboard/amd/romecrb "$@"
