#!/bin/sh

if [ -z "${DTC}" ]
then
	DTC=dtc
fi

TARGET_DIR="${PWD}/src/mainboard/amd/romecrb/target/x86_64-unknown-none/release"
mkdir -p "${TARGET_DIR}"
FIXED_DTFS=fixed-dtfs.dtb

"${DTC}" -W no-unit_address_vs_reg src/mainboard/amd/romecrb/fixed-dtfs.dts -O dtb -o "${TARGET_DIR}/${FIXED_DTFS}"

exec ../in-rust-nightly make OBJCOPY=objcopy -C src/mainboard/amd/romecrb "$@"
