#!/bin/sh
set -e

p="${PWD}"
exec docker run --rm -e RUST_TARGET_PATH="${RUST_TARGET_PATH}" -e TARGET_DIR="${TARGET_DIR}" -e PAYLOAD_A="${PAYLOAD_A}" -e USER="${USER}" --user "$(id -u)":"$(id -g)" -v "${PWD}:${PWD}" -w "${p}" rust-nightly-extra:latest "$@"
