#!/bin/sh
set -e

# MacOS X
command -v realpath >/dev/null 2>&1 || {
	realpath() {
		if ! [ "$1" = "${1#/*}" ]
		then
			echo -n "$1"
		else
			echo -n "${PWD}/${1#./}"
		fi
	}
}

root="${PWD}"

if [ "$1" = "-w" ]
then
	shift
	p="$1"
	p="`realpath \"${p}\"`"
	shift
else
	p="${PWD}"
fi

if [ "$1" = "-r" ]
then
	shift
	root="$1"
	root="`realpath \"${root}\"`"
	shift
fi

exec docker run --rm -e RUST_TARGET_PATH -e RUSTFLAGS -e TARGET_DIR -e PAYLOAD_A -e USER -e CARGO_NET_OFFLINE --user "$(id -u)":"$(id -g)" -v "${root}:${root}" -w "${p}" rust-nightly-extra:latest "$@"
