#!/bin/sh
set -e

root="${PWD}"

if [ "$1" = "-w" ]
then
	shift
	p="$1"
	p="`realpath \"${p}\"`"
	shift
else
	p="${PWD}"
fi

if [ "$1" = "-r" ]
then
	shift
	root="$1"
	root="`realpath \"${root}\"`"
	shift
fi

exec docker run --rm -e RUST_TARGET_PATH -e TARGET_DIR -e PAYLOAD_A -e USER --user "$(id -u)":"$(id -g)" -v "${root}:${root}" -w "${p}" rust-nightly-extra:latest "$@"
