#!/bin/sh

set -e
d="${PWD}"
psptool -C -o a.img && mv a.img "${d}/src/mainboard/amd/romecrb/initial.img"
(cd src/mainboard/amd/romecrb && guix environment --ad-hoc go -- go run patch.go -in initial.img -out final.fd)
echo "src/mainboard/amd/romecrb/final.fd"
